web_parking_app1/models.py
from django.db import models

class ParkingLot(models.Model):
    name = models.CharField(max_length=255)
    number_of_parking = models.IntegerField()
    parking_limit = models.IntegerField()

    def __str__(self):
        return self.name

class VehicleEntry(models.Model):
    parking_lot = models.ForeignKey(ParkingLot, on_delete=models.CASCADE)
    vehicle_registration_Name = models.CharField(max_length=255, unique=True, null=False)
    entry_time = models.DateTimeField(auto_now_add=True)
    exit_time = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.vehicle_name

templates/add_parking_lot.html
{% extends 'layout.html' %}  <!-- Assuming you have a base template -->

{% block content %}
  <h2>Add Parking Lot</h2>
  <form method="post">
    {% csrf_token %}  <!-- Include this for security reasons -->

    {{ form.as_p }}  <!-- Render the form fields -->

    <button type="submit">Submit</button>
  </form>
{% endblock %}

templates/carreview.html
{% extends "layout.html" %}
{% load custom_filters %}

{% block content %}
    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title"><i class="fa fa-cab"></i> Car Parking Data Table</h3>
                        <button type="button" class="btn btn-success btn-sm" style="margin-left: 2%" data-toggle="modal"
                                data-target="#add">
                            <i class="fa fa-plus"></i> Add
                        </button>
                        <!-- Add Modal -->
                        <div class="modal fade" id="add">
                            <div class="modal-dialog">
                                <form role="form" method="post" action="{% url 'add_parking_lot' %}">
                                    {% csrf_token %}
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal"
                                                    aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                            <h4 class="modal-title">Parking Information</h4>
                                        </div>
                                        <div class="modal-body">
                                            <div class="box box-primary">
                                                <div class="box-header with-border">
                                                    <h3 class="box-title">Fill In :</h3>
                                                </div>
                                                <div class="box-body">
                                                    <div class="form-group">
                                                        <label for="name">Name</label>
                                                        <input type="text" class="form-control" id="name"
                                                               name="name" placeholder="Enter Name">
                                                    </div>
                                                    <div class="form-group">
                                                        <label for="number_of_parking">Number of Parking</label>
                                                        <input type="number" class="form-control"
                                                               id="number_of_parking" name="number_of_parking"
                                                               placeholder="Enter Number of Parking">
                                                    </div>
                                                    <div class="form-group">
                                                        <label for="parking_limit">Parking Limit</label>
                                                        <input type="number" class="form-control"
                                                               id="parking_limit" name="parking_limit"
                                                               placeholder="Enter Parking Limit">
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-danger pull-left"
                                                    data-dismiss="modal">Close
                                            </button>
                                            <button type="submit" class="btn btn-primary">Submit</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                            <!-- /.modal-dialog -->
                        </div>
                        <!-- /.modal -->
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <table id="example1" class="table table-bordered table-striped">
                            <thead>
                            <tr style="background-color: #c5c5c5;">
                                <th style="width: 7%"><i class="fa fa-list-ol"></i> ID</th>
                                <th style="width: 23%"><i class="fa fa-user"></i>Parking Name</th>
                                <th style="width: 15%"><i class="fa fa-car"></i> Number of Parking</th>
                                <th style="width: 15%"><i class="fa fa-car"></i> Parking Limit</th>
                                <th style="width: 15%"><i class="fa fa-percent"></i> Parking Ratio</th>
                                <th style="width: 25%"></th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for parking_lot in parking_lots %}
                                <tr>
                                    <td>{{ parking_lot.id }}</td>
                                    <td><a href="{% url 'parking_lot_detail' parking_lot.id %}">{{ parking_lot.name }}</a>
                                    </td>
                                    <td>{{ parking_lot.number_of_parking }}</td>
                                    <td>{{ parking_lot.parking_limit }}</td>
                                    <td>
                                        {% with available_capacity=parking_lot.parking_limit|subtract:parking_lot.number_of_parking %}
                                            {% with available_percentage=available_capacity|multiply:100|div:parking_lot.parking_limit %}
                                                {{ available_percentage|floatformat:2 }}
                                            {% endwith %}
                                        {% endwith %}%
                                    </td>
                                    <td align="center">
                                        <button type="button" class="btn btn-primary btn-sm" data-toggle="modal"
                                                data-target="#edit{{ parking_lot.id }}"><i class="fa fa-pencil"></i>
                                        </button>
                                        <button type="button" class="btn btn-danger btn-sm"
                                                onclick="deleteParkingLot({{ parking_lot.id }})">
                                            <i class="fa fa-trash"></i> Delete
                                        </button>
                                    </td>
                                </tr>
                                <!-- Edit Modal -->
                                <div class="modal fade" id="edit{{ parking_lot.id }}">
                                    <div class="modal-dialog">
                                        <form role="form"
                                              method="post"
                                              action="{% url 'update_parking_lot' parking_lot.id %}">
                                            {% csrf_token %}
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <button type="button" class="close" data-dismiss="modal"
                                                            aria-label="Close">
                                                        <span aria-hidden="true">&times;</span>
                                                    </button>
                                                    <h4 class="modal-title">Update Parking Lot</h4>
                                                </div>
                                                <div class="modal-body">
                                                    <div class="box box-warning">
                                                        <div class="box-header with-border">
                                                        </div>
                                                        <div class="box-body">
                                                            <div class="form-group">
                                                                <label for="name">Name</label>
                                                                <input type="text" class="form-control" id="name"
                                                                       name="name"
                                                                       value="{{ parking_lot.name }}">
                                                            </div>
                                                            <div class="form-group">
                                                                <label for="number_of_parking">Number of Parking</label>
                                                                <input type="number" class="form-control"
                                                                       id="number_of_parking" name="number_of_parking"
                                                                       value="{{ parking_lot.number_of_parking }}">
                                                            </div>
                                                            <div class="form-group">
                                                                <label for="parking_limit">Parking Limit</label>
                                                                <input type="number" class="form-control"
                                                                       id="parking_limit" name="parking_limit"
                                                                       value="{{ parking_lot.parking_limit }}">
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-danger pull-left"
                                                            data-dismiss="modal">Close
                                                    </button>
                                                    <button type="submit" class="btn btn-primary">Update</button>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                    <!-- /.modal-dialog -->
                                </div>
                                <!-- /.modal -->
                            {% endfor %}
                            </tbody>
                            <tfoot>
                            <tr style="background-color: #c5c5c5;">
                                <th>ID</th>
                                <th>Name</th>
                                <th>Number of Parking</th>
                                <th>Parking Limit</th>
                                <th>Parking Ratio</th>
                                <th></th>
                            </tr>
                            </tfoot>
                        </table>
                    </div>
                    <!-- /.box-body -->
                </div>
                <!-- /.box -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->
{% block extra_scripts %}
<script>
    function deleteParkingLot(parkingLotId) {
        if (confirm('Are you sure you want to delete this parking lot?')) {
            // Send an AJAX request to delete the parking lot
            fetch(`/parking_lot/delete/${parkingLotId}/`, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRFToken': '{{ csrf_token }}'
                }
            })
                .then(response => {
                    if (response.redirected) {
                        window.location.href = response.url;  // Redirect to the parking lot list page
                    }
                });
        }
    }
</script>
{% endblock extra_scripts %}

{% endblock content %}

templates/error.html
{% extends "layout.html" %}
{% block content %}
    <h2>Error</h2>
    <p>{{ error_message }}</p>
{% endblock %}

templates/layout.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Car Parking System</title>
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <link rel="stylesheet" href="{% static 'bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'bower_components/font-awesome/css/font-awesome.min.css' %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="{% static 'bower_components/Ionicons/css/ionicons.min.css' %}">
  <!-- DataTables -->
  <link rel="stylesheet" href="{% static 'bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/AdminLTE.min.css' %}">
  <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
  <link rel="stylesheet" href="{% static 'dist/css/skins/_all-skins.min.css' %}">

   <!-- Favicons -->
   <link href="{% static 'dist/img/cropped-site_icon-32x32.png' %}" rel="icon">
   <link href="{% static 'dist/img/cropped-site_icon-32x32.png' %}" rel="apple-touch-icon">

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

  <!-- Google Font -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">

  {% block extra_styles %}{% endblock %}
</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">

  <header class="main-header">
    <!-- Logo -->
    <a href="{% url 'home' %}" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><b><i class="fa fa-cab"></i></b></span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"><b><i class="fa fa-cab"></i> Car</b>Parking</span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>



<!--User Right Side Panlel-->

      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
          <li class="dropdown user user-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <img src="{% static 'dist/img/avatar5.png' %}" class="user-image" alt="User Image">
              <span class="hidden-xs">{{ user.username }}</span>
            </a>
            <ul class="dropdown-menu">
              <!-- User image -->
              <li class="user-header">
                {% if user.profile_picture %}
                      <img src="{{ user.profile_picture.url }}" class="img-circle" alt="User Image">
                  {% else %}
                  <img src="{% static 'dist/img/avatar5.png' %}" class="img-circle" alt="User Image">
                  {% endif %}

                <p>
                  {{user.full_name}}
                  <small>{{user.email}}</small>
                </p>
              </li>
              <!-- Menu Footer-->
              <li class="user-footer">
                <div class="pull-left">
                  
                </div>
                <div class="pull-right">
                  <a href="{% url 'admin_logout' %}" class="btn btn-default btn-flat">Sign out</a>
                </div>
              </li>
            </ul>
          </li>
        </ul>
      </div>
    </nav>
  </header>

  <!-- Left side column. contains the logo and sidebar -->
  <aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel">
        <div class="pull-left image">
          <img src="{% static 'dist/img/avatar5.png' %}" class="img-circle" alt="User Image">
        </div>
        <div class="pull-left info">
          <p>{{user.full_name}}</p>
          <!-- Status -->
          <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <ul class="sidebar-menu" data-widget="tree">
        <li class="header">MAIN NAVIGATION</li>
        <!-- Optionally, you can add icons to the links -->
        <li><a href="{% url 'admin_dashboard' %}"><i class="fa fa-dashboard"></i> <span>Dashboard</span></a></li>
      </ul>
      <!-- /.sidebar-menu -->
    </section>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-md-12">
          {% block content %}
          {% endblock %}
        </div>
      </div>
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  <footer class="main-footer">
    <div class="pull-right hidden-xs">
      <b>Version</b> 1.0.0
    </div>
    <strong>Car Parking System</strong>
  </footer>
</div>
<!-- ./wrapper -->

<script src="{% static 'bower_components/jquery/dist/jquery.min.js' %}"></script>
<script src="{% static 'bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
<!-- DataTables -->
<script src="{% static 'bower_components/datatables.net/js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js' %}"></script>
<!-- SlimScroll -->
<script src="{% static 'bower_components/jquery-slimscroll/jquery.slimscroll.min.js' %}"></script>
<!-- FastClick -->
<script src="{% static 'bower_components/fastclick/lib/fastclick.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'dist/js/adminlte.min.js' %}"></script>
<script>
  $(function () {
    $('#example1').DataTable()
    $('#example2').DataTable({
      'paging'      : true,
      'lengthChange': false,
      'searching'   : false,
      'ordering'    : true,
      'info'        : true,
      'autoWidth'   : false
    })
  })
</script>

{% block extra_scripts %}{% endblock %}
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html>
<head>
    <title>User Login</title>
    {% load static %}
    <!DOCTYPE html>
    <html>
    <head>
        <title>Admin Login</title>
        <!-- Include the CSS files -->
        <link rel="stylesheet" href="{% static 'bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'bower_components/font-awesome/css/font-awesome.min.css' %}">
        <link rel="stylesheet" href="{% static 'bower_components/Ionicons/css/ionicons.min.css' %}">
        <link rel="stylesheet" href="{% static 'dist/css/AdminLTE.min.css' %}">
        <link rel="stylesheet" href="{% static 'plugins/iCheck/square/blue.css' %}">
        <!-- Include your custom CSS file if needed -->
    
        <!-- Include the JavaScript files -->
        <script src="{% static 'bower_components/jquery/dist/jquery.min.js' %}"></script>
        <script src="{% static 'bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
        <script src="{% static 'plugins/iCheck/icheck.min.js' %}"></script>
        <script>
            $(function () {
                $('input').iCheck({
                    checkboxClass: 'icheckbox_square-blue',
                    radioClass: 'iradio_square-blue',
                    increaseArea: '20%' /* optional */
                });
            });
        </script>
    </head>
    <body class="hold-transition login-page">
    <div class="login-box">
        <div class="login-logo">
            <a href="{% url 'dashboard' %}"><b>Car</b>Parking</a>
        </div>
        <!-- /.login-logo -->
        <div class="login-box-body">
            <p class="login-box-msg">Log in to start your session</p>
    
            <form method="post">
                {% csrf_token %}
                <div class="form-group has-feedback">
                    <input type="text" class="form-control" id="username" name="username" placeholder="Username">
                    <span class="glyphicon glyphicon-user form-control-feedback"></span>
                </div>
                <div class="form-group has-feedback">
                    <input type="password" class="form-control" id="password" name="password" placeholder="Password">
                    <span class="glyphicon glyphicon-lock form-control-feedback"></span>
                </div>
                <div class="row">
                    <div class="col-xs-8">
                        <div class="checkbox icheck">
                            <label>
                                <input type="checkbox"> Remember Me
                            </label>
                        </div>
                    </div>
                    <!-- /.col -->
                    <div class="col-xs-4">
                        <button type="submit" class="btn btn-primary btn-block btn-flat">Sign In</button>
                    </div>
                    <!-- /.col -->
                </div>
                
            </form>
    
            <!-- /.social-auth-links -->
    
        </div>
        <!-- /.login-box-body -->
    </div>
    <!-- /.login-box -->
    </body>
    </html>
    

templates/parking_lot_detail.html
{% extends "layout.html" %}
{% load static %}
{% block content %}

<!-- Main content -->
<section class="content">
    <div class="row text-center"> <!-- Add the 'text-center' class here -->
        <div class="col-xs-12 col-md-6 col-md-offset-3"> <!-- Use 'col-md-offset-3' to center align the column -->
            <div class="box">
                <div class="box-header">
                    <h1>Parking Lot Details</h1>
                    <p>車の出入りボタン</p>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <p><strong><b>Parking Name (駐車場名):</strong> {{ parking_lot.name }}</b></p>
                    <p><strong>Number of Parking (駐車台数):</strong> {{ parking_lot.number_of_parking }}</p>
                    <p class="text-red"><strong>Parking Limit (駐車可能台数):</strong> {{ parking_lot.parking_limit }}</p>
                    <form method="post" action="{% url 'parking_lot_detail' parking_lot.id %}">
                        {% csrf_token %}
                        <button class="btn btn-success btn-sm" type="submit" name="in">In</button>
                        <button class="btn btn-danger btn-sm" type="submit" name="out">Out</button>
                    </form>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>
<!-- /.content -->

{% endblock %}

templates/parking_lot_in_out.html
{% extends "layout.html" %}
{% load static %}
{% block content %}

<!-- Main content -->
<section class="content">
    <div class="row text-center">
        <div class="col-xs-12 col-md-6 col-md-offset-3">
            <!-- Display messages -->
            {% if messages %}
            <div class="messages">
                {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                {% endfor %}
            </div>
            {% endif %}

            <div class="box">
                <div class="box-header">
                    <h1>Parking Lot Details</h1>
                    <p>車の出入りボタン</p>
                </div>
                <div class="box-body">
                    <p><strong><b>Parking Name (駐車場名):</strong> {{ parking_lot.name }}</b></p>
                    <p><strong>Number of Parking (駐車台数):</strong> {{ parking_lot.number_of_parking }}</p>
                    <p class="text-red"><strong>Parking Limit (駐車可能台数):</strong> {{ parking_lot.parking_limit }}</p>
                    <form method="post" action="{% url 'parking_lot_detail' parking_lot_id=parking_lot.id %}">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="vehicle_registration_Name">Vehicle registration Name:</label>
                            <input type="text" class="form-control" id="vehicle_registration_Name" name="vehicle_registration_Name" placeholder="Enter Vehicle Name" required>
                        </div>
                        <button class="btn btn-success btn-sm" type="submit" name="in">In</button>
                    </form>
                    <form method="post" action="{% url 'parking_lot_detail' parking_lot_id=parking_lot.id %}">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="entry_id">Entry ID:</label>
                            <input type="text" class="form-control" id="entry_id" name="entry_id" placeholder="Enter Entry ID" required>
                        </div>
                        <button class="btn btn-danger btn-sm" type="submit" name="out">Out</button>
                    </form>
                    <form method="post" action="{% url 'delete_all_entries' parking_lot_id=parking_lot.id %}">
                        {% csrf_token %}
                        <button class="btn btn-danger btn-sm" style="margin-top: 10px;" type="submit" name="delete_all">ALL Delete</button>
                    </form>
                </div>
            </div>

            <!-- Vehicle Entries Table -->
            <div class="box">
                <div class="box-header">
                    <h2>Vehicle Entries</h2>
                </div>
                <div class="box-body">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>Vehicle registration Name</th>
                                <th>Entry Time</th>
                                <th>Exit Time</th>
                                <th>Print</th>
                                <th>Delete</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for entry in parking_lot.vehicleentry_set.all %}
                            <tr>
                                <td>{{ entry.vehicle_registration_Name }}</td>
                                <td>{{ entry.entry_time }}</td>
                                <td>{{ entry.exit_time|default:"N/A" }}</td>
                                <td>
                                    <button class="btn btn-primary btn-sm" onclick="printRow('{{ entry.vehicle_registration_Name }}', '{{ entry.entry_time }}', '{{ entry.exit_time|default:"N/A" }}')">Print</button>
                                </td>
                                <td>
                                    <form method="post" action="{% url 'delete_vehicle_entry' entry_id=entry.id %}">
                                        {% csrf_token %}
                                        <button class="btn btn-danger btn-sm" type="submit" name="delete">Delete</button>
                                    </form>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>


<script>
    function printRow(vehicleName, entryTime, exitTime) {
        var printContents = '<div style="text-align: center; padding: 20px;">' +
            '<h3 style="text-decoration: underline;">Vehicle Details</h3>' +
            '<p style="margin: 10px;"><strong>Vehicle Registration Name:</strong> ' + vehicleName + '</p>' +
            '<p style="margin: 10px;"><strong>Entry Time:</strong> ' + entryTime + '</p>' +
            '<p style="margin: 10px;"><strong>Exit Time:</strong> ' + (exitTime === 'N/A' ? 'N/A' : exitTime) + '</p>' +
            '</div>';

        var popupWin = window.open('', '_blank', 'fullscreen=yes');
        popupWin.document.open();
        popupWin.document.write('<html><head><title>Print</title>' +
            '<style>@media print { body { margin: 0; } }</style>' +
            '</head><body onload="window.print()">' + printContents + '</body></html>');
        popupWin.document.close();
    }
</script>





{% endblock %}